name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}
  MISE_AUTO_INSTALL: 'false'

jobs:
  run-mise-task:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Mise
        uses: jdx/mise-action@v2
        with:
          install: false

      - name: Create ~/.config/mise/config.toml
        run: |
          mkdir -p ~/.config/mise
          cat >~/.config/mise/config.toml <<EOF
          [tools]
          tuist = "4.40.0"
          age = "1.2.1"
          awscli = "2.23.3"
          direnv = "2.35.0"
          jq = "1.7.1"
          ruby = "3.3.3"
          sops = "3.9.3"
          sourcery = "2.2.6"
          swiftformat = "0.54.0"
          swiftlint = "0.58.2"
          yq = "4.45.1"
          xcbeautify = "2.23.0"
          "spm:mono0926/LicensePlist" = "3.25.1"
          "ubi:cli/cli" = { version = "2.65.0", exe = "gh" }
          "ubi:git-lfs/git-lfs" = "3.6.1"
          xcodes = "1.6.0"
          node = "23.6.1"
          pnpm = "10.0.0"
          [settings]
          experimental = true
          task_output = "quiet"
          EOF

      - name: Run Mise Task
        run: |
          for i in $(seq 1 20000); do mise test $i; done
