name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  run-mise-task:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Mise
        uses: jdx/mise-action@v2
        with:
          install: false

      - name: Create ~/.config/mise/config.toml
        run: |
          mkdir -p ~/.config/mise
          cat >~/.config/mise/config.toml <<EOF
          [tools]
          age = "1.2.1"
          EOF

      - name: Run Mise Task
        run: |
          for i in $(seq 1 20000); do mise test $i; done
